version: "3"

services:
    mongoDb:
        image: mongo
        container_name: api-mongo
    mongo_seeder:
        build:
            context: ./data/
            dockerfile: Dockerfile
        depends_on:
            - mongoDb
    web-api:
        container_name: web-api
        build:
            context: .
            dockerfile: src/HawkSoft.CodingAssessment.Api/Dockerfile
        depends_on:
            - mongoDb
            - mongo_seeder
